/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swingworldhibernate;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;
import org.hibernate.Session;
import pojos.City;
import pojos.Country;

/**
 *
 * @author nagyg
 */
public class Foablak extends javax.swing.JFrame {

    private DefaultTableModel dtm;
    private List<City> varosok;
    private List<Country> orszagok;
    private Country kivalasztottOrszag;
    private City kivalasztottVaros;

    public Foablak() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Országok-városok listázása");
        dtm = (DefaultTableModel) tblVarosok.getModel();
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                sajatClose();
            }
        });
    }

    public void sajatClose() {
        hibernate.HibernateUtil.getSessionFactory().close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstOrszagok = new javax.swing.JList<>();
        tfOrszag = new javax.swing.JTextField();
        btnKeres = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVarosok = new javax.swing.JTable();
        btnUj = new javax.swing.JButton();
        btnModosit = new javax.swing.JButton();
        btnTorol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Ország:");

        lstOrszagok.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lstOrszagok.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstOrszagok.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstOrszagokValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstOrszagok);

        tfOrszag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfOrszag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfOrszagActionPerformed(evt);
            }
        });
        tfOrszag.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfOrszagKeyReleased(evt);
            }
        });

        btnKeres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnKeres.setText("Keresés");
        btnKeres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeresActionPerformed(evt);
            }
        });

        tblVarosok.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblVarosok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Név", "Megye", "Lakosság"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblVarosok);

        btnUj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUj.setText("Új");
        btnUj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUjActionPerformed(evt);
            }
        });

        btnModosit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnModosit.setText("Módosít");
        btnModosit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModositActionPerformed(evt);
            }
        });

        btnTorol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTorol.setText("Töröl");
        btnTorol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTorolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfOrszag)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKeres)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUj)
                            .addComponent(btnModosit)
                            .addComponent(btnTorol))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfOrszag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKeres))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUj)
                        .addGap(40, 40, 40)
                        .addComponent(btnModosit)
                        .addGap(46, 46, 46)
                        .addComponent(btnTorol)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstOrszagokValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstOrszagokValueChanged
        kivalasztottOrszag = lstOrszagok.getSelectedValue();

        if (kivalasztottOrszag != null) {
            varosok = new ArrayList<>(kivalasztottOrszag.getCities());
//            for (City c : kivalasztottOrszag.getCities()) {
//                varosok.add(c);
//            }

            tablaFrissit();

        }
    }//GEN-LAST:event_lstOrszagokValueChanged

    private void tfOrszagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfOrszagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfOrszagActionPerformed

    private void tfOrszagKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfOrszagKeyReleased
        btnKeresActionPerformed(null);
    }//GEN-LAST:event_tfOrszagKeyReleased

    private void btnKeresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeresActionPerformed
        Session session = hibernate.HibernateUtil.getSessionFactory().openSession();
        String orszagNev = tfOrszag.getText();
        Query q = session.createQuery("FROM Country WHERE name LIKE :orszagNev");
        q.setString("orszagNev", orszagNev + "%");
        orszagok = q.list();

        lstOrszagok.setListData(new Vector<Country>(orszagok));
        varosok = null;
        tablaFrissit();

        session.close();
       

    }//GEN-LAST:event_btnKeresActionPerformed

    private void btnUjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUjActionPerformed

    }//GEN-LAST:event_btnUjActionPerformed

    private void btnModositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModositActionPerformed


    }//GEN-LAST:event_btnModositActionPerformed

    private void btnTorolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTorolActionPerformed


    }//GEN-LAST:event_btnTorolActionPerformed
    public void tablaFrissit() {
        dtm.getDataVector().clear();
        dtm.fireTableDataChanged();
        if (varosok != null) {
            for (City c : varosok) {
                Vector sor = new Vector();
                sor.add(c.getName());
                sor.add(c.getDistrict());
                sor.add(c.getPopulation());
                dtm.addRow(sor);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Foablak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeres;
    private javax.swing.JButton btnModosit;
    private javax.swing.JButton btnTorol;
    private javax.swing.JButton btnUj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Country> lstOrszagok;
    private javax.swing.JTable tblVarosok;
    private javax.swing.JTextField tfOrszag;
    // End of variables declaration//GEN-END:variables
}
